[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "ocbc-app"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9"
streamlit = "*"
plotly = "*"
