[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit-app"
version = "0.1.0"
requires-python = ">=3.9"

dependencies = [
    "streamlit",
    "plotly"
]
